#!/bin/sh

# If $1 is '-n', then we're being used like 'head -n 8 filename'
[ "${1}" = "-n" ] && shift 1

# If $1 is readable, then we're being used like 'head filename'
if [ -r "${1}" ]; then
  lines=10
else
  lines="${1:-10}"
  # If used as e.g. 'head -10', strip the leading '-'
  lines="${lines#-}"
  [ "${#}" -ge 1 ] && shift 1
fi

# If lines equals 0, then don't process further
[ "${lines}" -eq 0 ] && exit 0

# Test whether we have further params i.e. files to parse
if [ "${#}" -gt 0 ]; then
    for param in "${@}"; do
        count=0
        if [ "${#}" -ge 2 ]; then
           printf -- '==> %s <==\n' "${param}"
        fi
        while IFS="$(printf '\n')" read -r line; do
            printf -- '%s\n' "${line}"
            count=$(( count + 1 ))
            [ "${count}" -eq "${lines}" ] && break
        done < "${param}"
        [ "${#}" -ge 2 ] && printf -- '%s\n' ""
    done
# Otherwise, we treat our input as stdin
else
    count=0
    while IFS="$(printf '\n')" read -r line; do
        printf -- '%s\n' "${line}"
        count=$(( count + 1 ))
        [ "${count}" -eq "${lines}" ] && return 0
    done
    [ -n "${line}" ] && printf -- '%s\n' "${line}"
fi
